-- default schema
DROP TABLE IF EXISTS redis;

CREATE TABLE redis (
    -- default generated first id is zero.
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    name VARCHAR(128) NOT NULL,
    group_name VARCHAR(128) NOT NULL,
    mode VARCHAR(128) DEFAULT 'cluster',
    role VARCHAR(128),
    master_name VARCHAR(128) DEFAULT '',
    node VARCHAR(128),
    config_template VARCHAR(128),
    config_text VARCHAR(128),
    install_path VARCHAR(128),
    status VARCHAR(128),
    status_version INT,
    old_server_host VARCHAR(128),
    old_server_port INT DEFAULT 6379,
    old_require_pass VARCHAR(128),
    version VARCHAR(128),
    properties VARCHAR(128)
);
